apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: blog-basicdata
  namespace: blog
spec:
  replicas: 3
  selector:
    matchLabels:
      project: blog
      app: basicdata
  template:
    metadata:
      labels:
        project: blog
        app: basicdata
    spec:
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - name: basicdata
        image: qyzhcaofei/basicdata:<BUILD_TAG>
        imagePullPolicy: Always
        env:
        - name: branch
          value: <BRANCH_NAME> 
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 600m
            memory: 4Gi
          requests:
            cpu: 300m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 20
        volumeMounts:
        - name: jdk
          mountPath: /usr/local/jdk
      volumes:
      - name: jdk
        hostPath:
          path: /usr/local/jdk
          
---
apiVersion: v1
kind: Service
metadata:
  name: blog-basicdata
  namespace: blog
  labels:
    project: blog
    app: basicdata
spec:
  selector:
    project: blog
    app: basicdata
  ports:
  - name: web
    port: 80
    targetPort: 8080
    nodePort: 30007
  type: NodePort
